# Generated by Django 4.1.1 on 2023-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'AVAILABLE'), ('not available', 'NOT AVAILABLE')], default='confirmed', max_length=20),
        ),
    ]
