# Generated by Django 4.1.5 on 2023-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
