# Generated by Django 4.1.1 on 2023-01-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='status',
            new_name='confirmation_status',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='arrival_status',
            field=models.CharField(choices=[('confirmed', 'CONFIRMED'), ('pending', 'PENDING')], default='pending', max_length=20),
        ),
    ]
