# Generated by Django 4.1.1 on 2023-01-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservationmodel_confirmation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='arrival_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'CONFIRMED'), ('pending', 'PENDING')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'CONFIRMED'), ('pending', 'PENDING')], default='confirmed', max_length=20),
        ),
    ]
