# Generated by Django 4.1.1 on 2023-01-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservationmodel_arrival_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='arrival_status',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='confirmation_status',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='user',
        ),
    ]
