# Generated by Django 4.1.1 on 2023-01-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_reservationmodel_preference_reservationmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='arrival_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'CONFIRMED'), ('pending', 'PENDING')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'CONFIRMED'), ('pending', 'PENDING')], default='confirmed', max_length=20),
        ),
    ]
