# Generated by Django 4.1.1 on 2023-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservationmodel_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum_guest', models.IntegerField()),
                ('maximum_guest', models.IntegerField()),
                ('arrival_status', models.CharField(choices=[('available', 'AVAILABLE'), ('reserved', 'RESERVED'), ('occupied', 'OCCUPIED'), ('maintenance', 'MAINTENANCE')], default='available', max_length=20)),
            ],
        ),
    ]
