# Generated by Django 4.1.1 on 2023-01-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_tablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.tablemodel'),
        ),
    ]
