# Generated by Django 4.1.1 on 2023-01-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_reservationmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablemodel',
            old_name='arrival_status',
            new_name='status',
        ),
    ]
