# Generated by Django 4.1.1 on 2023-01-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_rename_arrival_status_tablemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='code',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
