# Generated by Django 4.1.1 on 2023-01-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_reservationmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('offline', 'OFFLINE'), ('online', 'ONLINE')], default='offline', max_length=20),
        ),
    ]
